=== Prateek-Rath/Hierarchical_KAnon/config/rules.xsd
<?xml version='1.0'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.xpriv.com/rules"
           xmlns="http://www.xpriv.com/rules"
           elementFormDefault="qualified">

    <xs:complexType name="subtreeType">
        <xs:attribute name="xpath" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="subtreeQuasiType">
        <xs:sequence>
            <xs:element name="AttributeManager" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="xpath" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="subtreeListType">
        <xs:sequence>
            <xs:element name="subtree" type="subtreeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="subtreeListQuasiType">
        <xs:sequence>
            <xs:element name="subtree" type="subtreeQuasiType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rules">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="attribute_mapping">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="direct" type="subtreeListType" minOccurs="0"/>
                            <xs:element name="quasi" type="subtreeListQuasiType" minOccurs="0"/>
                            <xs:element name="sensitive" type="subtreeListType" minOccurs="0"/>
                            <xs:element name="insensitive" type="subtreeListType" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="entity_level">
                    <xs:complexType>
                        <xs:attribute name="xpath" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Prateek-Rath/Hierarchical_KAnon/config/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<rules xmlns="http://www.xpriv.com/rules"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.xpriv.com/rules rules.xsd">

    <k_anonymity>2</k_anonymity>
    
    <attribute_mapping>
        <direct>
            <subtree xpath="/dataset/person/aadharNumber"/>
            <subtree xpath="/dataset/person/firstName"/>
            <subtree xpath="/dataset/person/lastName"/>
            <!-- <subtree xpath="/dataset/person/address/house/houseNumber"/> -->
            <!-- <subtree xpath="/dataset/person/address/house/street"/> -->
        </direct>
        
        <quasi>
            <subtree xpath="./age">
                <AttributeHandler>custom.AgeHandler.AgeHandler</AttributeHandler>
            </subtree>
            <!-- <subtree xpath="/dataset/person/gender">
                <AttributeHandler>suppression</AttributeHandler>
            </subtree>
            <subtree xpath="/dataset/person/occupation">
                <AttributeHandler>industry_generalization</AttributeHandler>
            </subtree>
            <subtree xpath="/dataset/person/education">
                <AttributeHandler>degree_level_generalization</AttributeHandler>
            </subtree>
            <subtree xpath="/dataset/person/maritalStatus">
                <AttributeHandler>suppression</AttributeHandler>
            </subtree> -->

            <!-- <subtree xpath="/dataset/person/address/location/city">
                <AttributeHandler>regional_generalization</AttributeHandler>
            </subtree>
            <subtree xpath="/dataset/person/address/location/state">
                <AttributeHandler>retention</AttributeHandler>
            </subtree>
            <subtree xpath="/dataset/person/address/location/pincode">
                <AttributeHandler>mask_last_3_digits</AttributeHandler> -->
            <!-- </subtree> -->
        </quasi>
        
        <sensitive>
            <subtree xpath="/dataset/person/disease"/>
            <subtree xpath="/dataset/person/incomeBracket"/>
        </sensitive>
        
        <insensitive>
            <subtree xpath="/dataset/person/bloodGroup"/>
            <subtree xpath="/dataset/person/address/location/country"/>
        </insensitive>
    </attribute_mapping>
    
    <entity_level xpath="/dataset/*"></entity_level>
    
</rules>
